# Generated by Django 5.2.6 on 2025-09-26 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_options_alter_itemimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Erstellung'), ('update', 'Aktualisierung'), ('delete', 'Löschung')], max_length=12)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='inventory.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Änderungsprotokoll',
                'verbose_name_plural': 'Änderungsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
    ]
