# Generated by Django 5.2.6 on 2025-10-16 09:47

import inventory.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_options_alter_itemimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemchangelog',
            new_name='inventory_i_item_id_752305_idx',
            old_name='inventory_i_item_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='itemchangelog',
            new_name='inventory_i_user_id_2a546d_idx',
            old_name='inventory_i_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='itemchangelog',
            new_name='inventory_i_action_e807ad_idx',
            old_name='inventory_i_action_created_idx',
        ),
        migrations.AddField(
            model_name='item',
            name='wodis_inventory_number',
            field=models.CharField(blank=True, db_index=True, help_text='Optionale Inventarnummer aus Wodis', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(storage=inventory.storage.PrivateMediaStorage(), upload_to='item_attachments/'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['wodis_inventory_number'], name='inventory_i_wodis_i_160d2d_idx'),
        ),
    ]
